\documentclass[12pt]{article}

\usepackage{times}
\usepackage[margin = 1cm]{geometry}

\setlength{\parskip}{6pt}
\setlength{\parindent}{0pt}

\begin{document}

<<get_libraries_and_set_options, cache = FALSE, echo = TRUE, include = FALSE>>=
options(width = 60)
library(IMA)
library(xtable)
library(doParallel)
library(foreach)
cl <- makeCluster(12)
registerDoParallel(cl)

@

<<load_data, cache = TRUE, echo = FALSE, include = FALSE>>=
#load the mvalues, pvalue, and hm450 matrix
#hm450 is the complete annotation matrix
load("/proj/design/il450k/nest13/R/MvalueAnalysisStructures.RData")

dim(mvalues)
dim(hm450)
dim(pData)
##annot.full contains the full annotation information 
##for all the CpG probes in the 450k array
annot.full <- annot
rm(annot)
table(rownames(pData) == pData$nestid)

#load the behavioral scores
epi<-read.csv("NESTSR_IVERSEN_8_22_15.csv", as.is=TRUE)
dim(epi)
length(unique(epi$nestid)) == nrow(epi)
rownames(epi) <-epi$nestid

#merge patient info (race, age, etc) with behavioral scores
table(keep<-rownames(pData) %in% rownames(epi))
pData<-pData[keep,]
mvalues<-mvalues[,keep]
epi <- epi[rownames(pData),]
colnames(epi)[colnames(epi) %in% colnames(pData)]
pData<-cbind(pData,epi[,colnames(epi) != "nest_id"])

#delete rows for which we do not have mother's ADHD data
keep <- (!is.na(pData$asrs_ADHD))
pData <- pData[keep,]
mvalues <- mvalues[,keep]
dim(mvalues)
rm(keep)

#only keep those probes where SNPs are less than half a percent
table(hm450$KeepHalfPct)
table(rownames(hm450)==rownames(mvalues))
mvalues<-mvalues[hm450$KeepHalfPct,]
hm450<-hm450[hm450$KeepHalfPct,]
table(rownames(hm450)==rownames(mvalues))

#colnames of mvalues are the barcode
#rownames of pData are the nestid (nest id and sample id are equal)
#for duplicate samples we used the higher quality mvalues
#which leads pData$barcode not corresponding to colnames of mvalues
#set rownames of pData to colnames of mvalues which is the barcode
rownames(pData) <- colnames(mvalues)
@

<<scatterplot, cache = TRUE, echo = TRUE, include = TRUE>>=

bhv.vars <- c("~ BASC_AP", "BASC_HY", "BRF_ISCI", "BRF_FI", 
    "BRF_EMI", "BRF_GEC", "BRF_IN", "BRF_SF", "BRF_PO", "BRF_WM", "BRF_EC")
fmla <- paste(bhv.vars, collapse = '+')
pairs(as.formula(fmla), data = pData)
@
\end{document}
